### ISSUE TITLE
Unable to create json

### ISSUE THREAD

**Issue by BakaValen** [grimlockx/ADCSKiller#5]
Just installed on a fully updated Kali instance. 
exactly as your documentation described. 

![image](https://github.com/grimlockx/ADCSKiller/assets/30160557/2d9adf22-8175-4f55-81bb-3bf0b02fe000)

The image describes my error. 

What info or logs will you require to help debug please?
All the requirements were installed by your documented methods or were already there via kali repo. 

EDIT:  I have also done this on Parrot OS and the same error occurs.

**Comment by BakaValen** [comment]
[+] Authenticating to LDAP server
[-] Got error: Connection.__init__() got an unexpected keyword argument 'channel_binding'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.8.1-py3.11.egg/certipy/entry.py", line 60, in main
    actions[options.action](options)
  File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.8.1-py3.11.egg/certipy/commands/parsers/find.py", line 12, in entry
    find.entry(options)
  File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.8.1-py3.11.egg/certipy/commands/find.py", line 1179, in entry
    find.find()
  File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.8.1-py3.11.egg/certipy/commands/find.py", line 165, in find
    connection = self.connection
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.8.1-py3.11.egg/certipy/commands/find.py", line 124, in connection
    self._connection.connect()
  File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.8.1-py3.11.egg/certipy/lib/ldap.py", line 77, in connect
    self.connect(version=ssl.PROTOCOL_TLSv1_2)
  File "/usr/local/lib/python3.11/dist-packages/certipy_ad-4.8.1-py3.11.egg/certipy/lib/ldap.py", line 125, in connect
    ldap_conn = ldap3.Connection(
                ^^^^^^^^^^^^^^^^^
TypeError: Connection.__init__() got an unexpected keyword argument 'channel_binding'

This after running certipy on its own. 

Did something change in certipy?

**Comment by BakaValen** [comment]
rolling back certipy to certipy-ad 4.7.0 OR 4.8.0 allows things to run but still end up with the original issue of (see image)
![image](https://github.com/grimlockx/ADCSKiller/assets/30160557/241df3db-a35d-457e-801e-be3e86f7f2f0)

where it says it cant find a target.

**Comment by BakaValen** [comment]
changing the to a forked version of ldap3 (pip3 install git+https://github.com/ly4k/ldap3) allows everything to run but still dies at:

certipy relay: error: the following arguments are required: -target

**Comment by sec13b** [comment]
did you solve ?

**Comment by BakaValen** [comment]
> did you solve ?

No.  There is no progress on this bug.  Neither by this author or by certipy author.
